In [4]:
#7.1 处理缺失数据
import numpy as np
import pandas as pd
string_data = pd.Series(['aardvark','artichoke',np.nan])
string_data

0     aardvark
1    artichoke
2          NaN
dtype: object

In [5]:
string_data.isnull()

0    False
1    False
2     True
dtype: bool

In [6]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
dtype: bool

In [7]:
#滤除缺失值
from numpy import nan as NA
data = pd.Series([1,NA,3.5,NA,7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [8]:
#等价于
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
#在DataFrame中，dropna默认丢弃任何含有缺失值的行
data = pd.DataFrame([[1,6.5,3],[1,NA,NA],[NA,NA,NA],[NA,6.5,3]])
clean = data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [11]:
clean

0    1    2
0  1.0  6.5  3.0

In [12]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [14]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [15]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
df = pd.DataFrame(np.random.randn(7,3))
df.iloc[:4,1] = NA
df.iloc[:2,2] = NA
df

0         1         2
0  2.142223       NaN       NaN
1 -0.051855       NaN       NaN
2 -1.242260       NaN  0.895283
3  0.950544       NaN  0.596089
4 -0.327394  0.872652  0.782323
5 -0.132988  1.516506 -1.708739
6 -0.489088  1.182743  1.570135

In [17]:
df.dropna()

0         1         2
4 -0.327394  0.872652  0.782323
5 -0.132988  1.516506 -1.708739
6 -0.489088  1.182743  1.570135

In [18]:
df.dropna(thresh=2)

0         1         2
2 -1.242260       NaN  0.895283
3  0.950544       NaN  0.596089
4 -0.327394  0.872652  0.782323
5 -0.132988  1.516506 -1.708739
6 -0.489088  1.182743  1.570135

In [19]:
#填充缺失数据
df.fillna(0)

0         1         2
0  2.142223  0.000000  0.000000
1 -0.051855  0.000000  0.000000
2 -1.242260  0.000000  0.895283
3  0.950544  0.000000  0.596089
4 -0.327394  0.872652  0.782323
5 -0.132988  1.516506 -1.708739
6 -0.489088  1.182743  1.570135

In [20]:
df.fillna({1:0.5,2:0})

0         1         2
0  2.142223  0.500000  0.000000
1 -0.051855  0.500000  0.000000
2 -1.242260  0.500000  0.895283
3  0.950544  0.500000  0.596089
4 -0.327394  0.872652  0.782323
5 -0.132988  1.516506 -1.708739
6 -0.489088  1.182743  1.570135

In [22]:
_ = df.fillna(0,inplace=True)
df

0         1         2
0  2.142223  0.000000  0.000000
1 -0.051855  0.000000  0.000000
2 -1.242260  0.000000  0.895283
3  0.950544  0.000000  0.596089
4 -0.327394  0.872652  0.782323
5 -0.132988  1.516506 -1.708739
6 -0.489088  1.182743  1.570135

In [24]:
#对reindexing有效的那些插值方法也可用于fillna
df = pd.DataFrame(np.random.randn(6,3))
df.iloc[2:,1] = NA
df.iloc[4:,2] = NA
df

0         1         2
0 -0.226956 -0.409858 -1.306283
1 -1.009830  0.758684  0.372208
2  0.238355       NaN -1.186227
3 -0.923882       NaN -1.016287
4  0.437881       NaN       NaN
5 -0.328722       NaN       NaN

In [25]:
df.fillna(method='ffill')

0         1         2
0 -0.226956 -0.409858 -1.306283
1 -1.009830  0.758684  0.372208
2  0.238355  0.758684 -1.186227
3 -0.923882  0.758684 -1.016287
4  0.437881  0.758684 -1.016287
5 -0.328722  0.758684 -1.016287

In [26]:
df.fillna(method='ffill',limit=2)

0         1         2
0 -0.226956 -0.409858 -1.306283
1 -1.009830  0.758684  0.372208
2  0.238355  0.758684 -1.186227
3 -0.923882  0.758684 -1.016287
4  0.437881       NaN -1.016287
5 -0.328722       NaN -1.016287

In [27]:
data = pd.Series([1,NA,3.5,NA,7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [28]:
#7.2 数据转换
#移除重复数据
data = pd.DataFrame({'k1':['one','two']*3+['two'],
                    'k2':[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [29]:
#DataFrame的duplicated方法返回一个布尔型Series，表示各行是否是重复行
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [31]:
#该方法返回一个DataFrame，重复数组会标位False
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [32]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [34]:
#duplicated和drop_duplicates默认保留的是第一个出现的值组合
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

# 利用函数或映射进行数据转换

In [35]:
data = pd.DataFrame({'food':['bacon','pulled pork','Pastrmi','corned beef','pastrami','honey ham']
                    ,'ounces':[4,3,12,6,7.5,8]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2      Pastrmi    12.0
3  corned beef     6.0
4     pastrami     7.5
5    honey ham     8.0

In [41]:
meat_to_animal = {
    'bacon':'pig',
    'pulled pork':'pig',
    'Pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
}
#Serial的map方法可以接受一个函数或含有映射关系的字典类型对象
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2        pastrmi
3    corned beef
4       pastrami
5      honey ham
Name: food, dtype: object

In [42]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces animal
0        bacon     4.0    pig
1  pulled pork     3.0    pig
2      Pastrmi    12.0    NaN
3  corned beef     6.0    cow
4     pastrami     7.5    NaN
5    honey ham     8.0    pig

# 替换值

In [44]:
data = pd.Series([1,-999,2,-999,-1000,3])
data

0       1
1    -999
2       2
3    -999
4   -1000
5       3
dtype: int64

In [46]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [47]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [48]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

# 重命名轴索引

In [50]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),
                   index=['Ohio','Colorado','New York'],
                   columns=['one','two','three','four'])
transform = lambda x : x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [51]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [53]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [54]:
#rename可以结合字典型对象实现对部分轴标签的更新
data.rename(index={'OHIO':'INDIANA'},columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [55]:
data.rename(index={'OHIO':'INDIANA'},inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

# 离散化和面元划分

In [57]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]
bins = [18,25,35,60,100]
cats = pd.cut(ages,bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [59]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [60]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [61]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [62]:
pd.cut(ages,[18,26,36,61,100],right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [63]:
group_names = ['Youth','YoungAdult','MiddleAged','Seniordle']
pd.cut(ages,bins,labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Seniordle, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Seniordle]

In [65]:
data = np.random.randn(20)
pd.cut(data,4,precision=2)

[(-0.56, 0.29], (0.29, 1.14], (-0.56, 0.29], (-0.56, 0.29], (0.29, 1.14], ..., (-1.42, -0.56], (1.14, 1.99], (1.14, 1.99], (-0.56, 0.29], (0.29, 1.14]]
Length: 20
Categories (4, interval[float64]): [(-1.42, -0.56] < (-0.56, 0.29] < (0.29, 1.14] < (1.14, 1.99]]

In [66]:
data = np.random.randn(1000)
cats = pd.qcut(data,4)
cats

[(0.00157, 0.734], (0.00157, 0.734], (-0.659, 0.00157], (0.00157, 0.734], (-0.659, 0.00157], ..., (-0.659, 0.00157], (0.00157, 0.734], (0.734, 2.834], (-0.659, 0.00157], (-0.659, 0.00157]]
Length: 1000
Categories (4, interval[float64]): [(-3.606, -0.659] < (-0.659, 0.00157] < (0.00157, 0.734] < (0.734, 2.834]]

In [67]:
pd.value_counts(cats)

(0.734, 2.834]       250
(0.00157, 0.734]     250
(-0.659, 0.00157]    250
(-3.606, -0.659]     250
dtype: int64

In [68]:
pd.qcut(data,[0,0.1,0.5,0.9,1])

[(0.00157, 1.368], (0.00157, 1.368], (-1.3, 0.00157], (0.00157, 1.368], (-1.3, 0.00157], ..., (-1.3, 0.00157], (0.00157, 1.368], (0.00157, 1.368], (-1.3, 0.00157], (-1.3, 0.00157]]
Length: 1000
Categories (4, interval[float64]): [(-3.606, -1.3] < (-1.3, 0.00157] < (0.00157, 1.368] < (1.368, 2.834]]

# 检测和过滤异常值

In [69]:
data = pd.DataFrame(np.random.randn(1000,4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.026285    -0.046545     0.024480    -0.037448
std       0.995008     0.966356     1.023570     1.002464
min      -3.399112    -2.993632    -3.134106    -3.436523
25%      -0.677044    -0.682495    -0.617697    -0.743272
50%      -0.016515    -0.048532     0.043073    -0.055881
75%       0.644009     0.599292     0.737817     0.605565
max       2.916203     3.473971     3.261767     3.101419

In [71]:
col = data[2]
col[np.abs(col) > 3]

27    -3.134106
481    3.261767
Name: 2, dtype: float64

In [72]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
27  -2.098892 -1.264865 -3.134106 -0.830072
479 -3.165776 -0.469171  0.110560 -0.057853
481  0.706927  0.236046  3.261767 -0.036881
505  0.129802  0.274876  2.099370 -3.436523
682 -1.139577  1.108772  1.091068  3.101419
750  0.926014  3.473971 -0.746226  0.537941
924 -3.399112 -0.877393  0.383862 -0.105057

In [73]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.025720    -0.047019     0.024352    -0.037113
std       0.993222     0.964743     1.022368     1.000764
min      -3.000000    -2.993632    -3.000000    -3.000000
25%      -0.677044    -0.682495    -0.617697    -0.743272
50%      -0.016515    -0.048532     0.043073    -0.055881
75%       0.644009     0.599292     0.737817     0.605565
max       2.916203     3.000000     3.000000     3.000000

In [74]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0 -1.0  1.0
1  1.0 -1.0  1.0 -1.0
2  1.0 -1.0 -1.0 -1.0
3  1.0 -1.0  1.0 -1.0
4  1.0 -1.0  1.0 -1.0

# 排列和随机取样

In [75]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5,4)))
sampler = np.random.permutation(5)
sampler

array([0, 2, 4, 1, 3])

In [76]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [77]:
df.take(sampler)

0   1   2   3
0   0   1   2   3
2   8   9  10  11
4  16  17  18  19
1   4   5   6   7
3  12  13  14  15

In [78]:
df.sample(n=3)

0   1   2   3
0   0   1   2   3
4  16  17  18  19
2   8   9  10  11

In [79]:
choices = pd.Series([5,7,-1,6,4])
draws = choices.sample(n=10,replace=True)
draws

2   -1
1    7
3    6
0    5
1    7
1    7
3    6
2   -1
1    7
0    5
dtype: int64

# 计算指标/哑变量

In [80]:
#另一种建模或机器学习的转换方式是将分类变量转换为“哑变量”或“指标矩阵”
df = pd.DataFrame({'key':['b','b','a','c','a','b'],
                  'data1':range(6)})
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [81]:
dummies = pd.get_dummies(df['key'],prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [82]:
np.random.seed(12345)
values = np.random.randn(10)
values

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474])

In [83]:
bins = [0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           0
1           0           0           1           0           0
2           0           0           0           0           0
3           0           0           0           0           0
4           0           0           0           0           0
5           0           0           0           0           0
6           1           0           0           0           0
7           0           1           0           0           0
8           0           0           0           1           0
9           0           0           0           0           0

In [87]:
mnames = ['movie_id','title','genres']
movies = pd.read_table('C:\Mine\Github\Python\movies.dat',
sep='::',
                       header=None,names=mnames)
movies[:10]

c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: read_table is deprecated, use read_csv instead.
  after removing the cwd from sys.path.
c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  after removing the cwd from sys.path.


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [88]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [90]:
zero_matrix = np.zeros((len(movies),len(genres)))
dummies = pd.DataFrame(zero_matrix,columns=genres)
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [91]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [93]:
for i,gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices] = 1
movies_windic = movies.join(dummies.add_prefix('Genre_movies'))
movies_windic.iloc[0]

movie_id                                             1
title                                 Toy Story (1995)
genres                     Animation|Children's|Comedy
Genre_moviesAnimation                                1
Genre_moviesChildren's                               1
Genre_moviesComedy                                   1
Genre_moviesAdventure                                0
Genre_moviesFantasy                                  0
Genre_moviesRomance                                  0
Genre_moviesDrama                                    0
Genre_moviesAction                                   0
Genre_moviesCrime                                    0
Genre_moviesThriller                                 0
Genre_moviesHorror                                   0
Genre_moviesSci-Fi                                   0
Genre_moviesDocumentary                              0
Genre_moviesWar                                      0
Genre_moviesMusical                                  0
Genre_movi

In [95]:
np.random.seed(12345)
values = np.random.randn(10)
values

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474])

In [96]:
bins = [0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           0
1           0           0           1           0           0
2           0           0           0           0           0
3           0           0           0           0           0
4           0           0           0           0           0
5           0           0           0           0           0
6           1           0           0           0           0
7           0           1           0           0           0
8           0           0           0           1           0
9           0           0           0           0           0

# 7.3 字符串操作

# 字符串对象方法

In [97]:
val = 'a,b,guido'
val.split(',')

['a', 'b', 'guido']

In [98]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [99]:
first,second,third = pieces
first + '::' + second + '::' +third

'a::b::guido'

In [100]:
'::'.join(pieces)

'a::b::guido'

In [101]:
'guido' in val

True

In [102]:
val.index(',')

1

In [103]:
val.find(':')

-1

In [104]:
val.index(':')

ValueError: substring not found

In [105]:
val.count(',')

2

In [106]:
val.replace(',','::')

'a::b::guido'

In [109]:
val.replace(',', '')

'abguido'

# 正则表达式

In [9]:
#re模块的函数可以分为三个大类：模式匹配，替换以及拆分
import re
text = "foo bar\t baz \tqux"
re.split('\s+',text)

['foo', 'bar', 'baz', 'qux']

In [10]:
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [11]:
regex.findall(text)

[' ', '\t ', ' \t']

In [19]:

text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [21]:
regex.findall(text)

[' ', '\n', ' ', '\n', ' ', '\n', ' ', '\n']

In [22]:
m = regex.search(text)
m

<_sre.SRE_Match object; span=(4, 5), match=' '>

In [23]:
text[m.start():m.end()]

' '

In [24]:
print(regex.match(text))

None


In [25]:
print(regex.sub('REDACTED',text))

DaveREDACTEDdave@google.comREDACTEDSteveREDACTEDsteve@gmail.comREDACTEDRobREDACTEDrob@gmail.comREDACTEDRyanREDACTEDryan@yahoo.comREDACTED


In [26]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
regex = re.compile(pattern,flags=re.IGNORECASE)

In [27]:
m = regex.match('wesm@bright.net')
m.groups()

()

In [28]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

# pandas的矢量化字符串函数

In [30]:
import pandas as pd
data = {'Dave':'dave@google.com','Steve':'steve@gmail.com','Rob':'rob@gmail.com'
       ,'Wes':'np.nan'}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes               np.nan
dtype: object

In [31]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes      False
dtype: bool

In [32]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes      False
dtype: bool

In [34]:
pattern

'[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,4}'

In [35]:
data.str.findall(pattern,flags=re.IGNORECASE)

Dave     [dave@google.com]
Steve    [steve@gmail.com]
Rob        [rob@gmail.com]
Wes                     []
dtype: object

In [36]:
matches = data.str.match(pattern,flags=re.IGNORECASE)
matches

Dave      True
Steve     True
Rob       True
Wes      False
dtype: bool

In [39]:
matches.get(1)

True

In [42]:
matches

Dave      True
Steve     True
Rob       True
Wes      False
dtype: bool

In [43]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes      np.na
dtype: object