In [1]:
#5.1 Pandas的数据结构介绍
#Series
import pandas as pd
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index #like range(4)

RangeIndex(start=0, stop=4, step=1)

In [12]:
import pandas as pd
obj2 = pd.Series([4,7,-5,3],index = ['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [13]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [15]:
obj2['a']

-5

In [16]:
obj2['d'] = 6
obj2[['c','a','d']]
#['c','a','d']为索引列表，字符串

c    3
a   -5
d    6
dtype: int64

In [17]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [18]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [19]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [20]:
#还可以将Series看成一个定长的有序字典
'b' in obj2

True

In [21]:
'e' in obj2

False

In [22]:
#如果数据被存放在一个Python字典中，也可以直接通过这个字典来创建Series
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
dtype: int64

In [23]:
#可以改变键的顺序
import pandas as pd
states = ['California','Ohio','Oregon','Texas']
obj4 = pd.Series(sdata,index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [24]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [26]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
dtype: int64

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
obj3 +obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
dtype: float64

In [30]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [31]:
#Series的索引可以通过赋值的方式就地修改:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [32]:
obj.index = ['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [36]:
#DataFram
import pandas as pd
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada']
        ,'year':[2000,2001,2002,2001,2002,2003]
        ,'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [37]:
#对于特别大的DataFrame,head方法会选取前五行
import pandas as pd
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [38]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [41]:
#如果传入数据中找不到，就会在结果中产生缺失值
frame2 =pd.DataFrame(data,columns=['year','state','pop','debt']
                    ,index=['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [42]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [43]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [45]:
frame.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [47]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [49]:
#列可以通过赋值的方式进行修改
frame2['debt'] = 16.5
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [51]:
import numpy as np
frame2['debt'] = np.arange(6)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [54]:
#将列表或数组赋值给某个列时，其长度必须跟DataFrame的长度匹配
val = pd.Series([-1.2,-1.5,-1.7]
                ,index=['two','four','three'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6  -1.7
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9   NaN
six    2003  Nevada  3.2   NaN

In [55]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2
#注意:不能用frame2.eastern创建新的列

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6  -1.7     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9   NaN    False
six    2003  Nevada  3.2   NaN    False

In [56]:
del frame2['eastern']
frame2.columns
#通过索引方式返回的列只是相应数据的视图而已，并不是副本。因此，
#对返回的Series所做的任何就地修改全都会反映到源DataFrame上。
#通过Series的copy方法即可指定复制列

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [58]:
#嵌套字典
pop = {'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [60]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [61]:
#如果明确指定了索引，则不会出现内层字典的键被合并、排序以形成最终的索引。
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [62]:
#由Series组成的字典差不多一样
pdata = {'Ohio':frame3['Ohio'][:-1],
          'Nevada':frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [63]:
#如果设置了DataFrame的index和columns的name属性,则这些信息也会被显示
frame3.index.name = 'year';
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [64]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [65]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, -1.7],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [67]:
#索引对象
obj = pd.Series(range(3),index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [68]:
index[1:]

Index(['b', 'c'], dtype='object')

In [70]:
#Index对象是不可变的，不能对其进行修改
#不可变可以使Index对象在多个数据结构之间安全共享
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [71]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [72]:
obj2.index is labels

True

In [73]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [74]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [75]:
'Ohio' in frame3.index

False

In [76]:
2003 in frame3.index

False

In [77]:
#pandas的Index可以包含重复的标签
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [79]:
#5.2 基本功能
#重新索引
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','c','a'])
obj

d    4.5
b    7.2
c   -5.3
a    3.6
dtype: float64

In [80]:
#用该Series的reindex将会根据新索引进行重排。若果某个索引值当前不存在，就引入缺失值。
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a    3.6
b    7.2
c   -5.3
d    4.5
e    NaN
dtype: float64

In [82]:
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [83]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [84]:
frame = pd.DataFrame(np.arange(9).reshape((3,3))
                     ,index=['a','b','c']
                     ,columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [85]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN

In [86]:
#列可以用columns关键字重新索引
states = ['Texas','Utah','California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
c      7   NaN           8

In [4]:
#丢弃指定轴上的项
import numpy as np
import pandas as pd
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [6]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [7]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [10]:
#DataFrame可以删除任意轴上的索引值
import pandas as pd
data = pd.DataFrame(np.arange(16).reshape((4,4))
                    ,index=['Ohio','Colorado','Utah','New York']
                   ,columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [11]:
#用标签序列调用drop会从行标签（axis=0）删除值
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [12]:
#可以通过传递axis=1或axis=‘columns’可以删除列的值
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [13]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [14]:
obj.drop('c',inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [ ]:
#######小心使用inplace，会销毁所有被删除的数据

In [15]:
#索引、选取和过滤
obj = pd.Series(np.arange(4),index=['a','b','c','d'])
obj

a    0
b    1
c    2
d    3
dtype: int32

In [16]:
obj['b']

1

In [17]:
obj[2:4]

c    2
d    3
dtype: int32

In [18]:
obj[['b','a','d']]

b    1
a    0
d    3
dtype: int32

In [19]:
obj[[1,3]]

b    1
d    3
dtype: int32

In [20]:
obj[obj < 2]

a    0
b    1
dtype: int32

In [21]:
#利用标签的 切片运算与Python不同。其末尾是包含的
obj['b':'c']

b    1
c    2
dtype: int32

In [22]:
obj['b':'c'] = 5
obj

a    0
b    5
c    5
d    3
dtype: int32

In [24]:
data = pd.DataFrame(np.arange(16).reshape((4,4))
                   ,index=['Ohio','Colorado','Utah','New York']
                   ,columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [25]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [26]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [27]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [28]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [29]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [30]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [31]:
#用轴标签（loc）和整数标签（iloc）进行选取
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [32]:
#然后用iloc和整数进行选取
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [33]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [34]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [35]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [36]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [39]:
#整数索引
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [40]:
ser2 = pd.Series(np.arange(3.),index=['a','b','c'])
ser2[-1]

2.0

In [41]:
ser[:1]

0    0.0
dtype: float64

In [42]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [43]:
ser.iloc[:1]

0    0.0
dtype: float64

In [45]:
#算术运算和数据对齐
#可以对不同索引的对象进行算术运算。
#在讲对象相加时，如果存在不同索引对，则结果的索引近视该索引对的并集
s1 = pd.Series([7.3,-2.5,3.4,1.5]
              ,index=['a','c','b','d'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1]
              ,index=['a','c','e','f','g'])
s1

a    7.3
c   -2.5
b    3.4
d    1.5
dtype: float64

In [46]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [47]:
s1 + s2

a    5.2
b    NaN
c    1.1
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [48]:
#对于DataFrame,对齐操作会发生在行和列上
df1 = pd.DataFrame(np.arange(9).reshape((3,3))
                  ,columns=['b','c','d']
                  ,index=['Ohio','Texas','Colorado'])
df2 = pd.DataFrame(np.arange(12).reshape((4,3))
                  ,columns=['b','c','e']
                  ,index=['Texas','Ohio','Texas','Oregon'])
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [49]:
df2

b   c   e
Texas   0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [51]:
df1 + df2

b     c   d   e
Colorado  NaN   NaN NaN NaN
Ohio      3.0   5.0 NaN NaN
Oregon    NaN   NaN NaN NaN
Texas     3.0   5.0 NaN NaN
Texas     9.0  11.0 NaN NaN

In [52]:
df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[3,4]})
df1

A
0  1
1  2

In [53]:
df2

B
0  3
1  4

In [55]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [56]:
#在算术方法中填充值
df1 = pd.DataFrame(np.arange(12).reshape((3,4)),columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20).reshape((4,5)),columns=list('abcde'))
df2.loc[1,'b'] = np.nan
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [57]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [58]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [59]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [60]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [61]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [64]:
#在对Series或DataFrame重新索引时，也可以指定一个填充值
df1.reindex(columns=df2.columns,fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

In [65]:
#DataFrame和Series之间的运算
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
arr[0]

array([0, 1, 2, 3])

In [67]:
arr - arr[0]
#这叫做广播

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [69]:
frame = pd.DataFrame(np.arange(12).reshape((4,3))
                    ,columns=list('bde')
                    ,index=['Utah','Ohio','Texas','Oregon'])
series = frame.iloc[0]
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [70]:
series

b    0
d    1
e    2
Name: Utah, dtype: int32

In [71]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [72]:
#如果某个索引值在DataFrame的列或Series的索引中找不到，则参加运算的两个对象就会被重新索引以形成并集
series2 = pd.Series(range(3),index=['b','e','f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [73]:
series3 = frame['d']
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [74]:
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int32

In [75]:
frame.sub(series3,axis='index')
#传入的轴号就是希望匹配的轴

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

In [78]:
#函数应用和映射
frame = pd.DataFrame(np.random.randn(4,3)
                    ,columns=list('bde')
                    ,index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah   -0.635577 -0.576797  0.155737
Ohio   -0.179604  2.004558 -1.726010
Texas  -0.304499  0.550572 -0.840894
Oregon -0.098984  1.340407 -0.644033

In [79]:
np.abs(frame)

b         d         e
Utah    0.635577  0.576797  0.155737
Ohio    0.179604  2.004558  1.726010
Texas   0.304499  0.550572  0.840894
Oregon  0.098984  1.340407  0.644033

In [84]:
f = lambda x : x.max() - x.min()
frame.apply(f)

b    0.536593
d    2.581355
e    1.881747
dtype: float64

In [85]:
#如果传递axis=‘columns’到apply，这个函数会在每行执行
frame.apply(f,axis='columns')

Utah      0.791314
Ohio      3.730568
Texas     1.391466
Oregon    1.984441
dtype: float64

In [86]:
def f(x):
    return pd.Series([x.min(),x.max()]
                    ,index=['min','max'])
frame.apply(f)

b         d         e
min -0.635577 -0.576797 -1.726010
max -0.098984  2.004558  0.155737

In [88]:
format = lambda x : '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -0.64  -0.58   0.16
Ohio    -0.18   2.00  -1.73
Texas   -0.30   0.55  -0.84
Oregon  -0.10   1.34  -0.64

In [89]:
frame['e'].map(format)

Utah       0.16
Ohio      -1.73
Texas     -0.84
Oregon    -0.64
Name: e, dtype: object

In [90]:
#排序和排名
obj = pd.Series(range(4),index=['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [91]:
#对于DataFrame，则可以根据任意一个轴上的索引进行排序
frame = pd.DataFrame(np.arange(8).reshape((2,4))
                    ,index=['three','one']
                    ,columns=['d','a','b','c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [92]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [93]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [94]:
obj = pd.Series([4,7,-3,2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [95]:
#任何缺失值默认都会被放到Series的末尾
obj = pd.Series([4,np.nan,7,np.nan,-3,2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [96]:
frame = pd.DataFrame({'b':[4,7,-3,2]
                     ,'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [97]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [98]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [100]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [101]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [103]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [104]:
frame =  pd.DataFrame({'b':[4.3,7,-3,2]
                      ,'a':[0,1,0,1]
                      ,'c':[-2,5,8,-2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [105]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [106]:
#带有重复标签的轴索引
obj = pd.Series(range(5)
               ,index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [107]:
#索引值的is_unique属性可以告诉你它的值是否唯一
obj.index.is_unique

False

In [108]:
obj['a']

a    0
a    1
dtype: int64

In [109]:
obj['c']

4

In [110]:
df = pd.DataFrame(np.random.randn(4,3)
                 ,index=['a','a','b','b'])
df

0         1         2
a -0.827761 -0.731761 -1.559420
a  0.118944  1.825988  1.117761
b  1.891534  0.359997 -1.108463
b -1.688823 -0.667755  1.717850

In [111]:
df.loc['b']

0         1         2
b  1.891534  0.359997 -1.108463
b -1.688823 -0.667755  1.717850

In [112]:
#5.3 汇总和计算描述统计
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]]
                  ,index=['a','b','c','d']
                 ,columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [113]:
#调用DataFrame的sum方法将会返回一个含有列的和的Series
df.sum()

one    9.25
two   -5.80
dtype: float64

In [114]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [117]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [118]:
df.idxmax()

one    b
two    d
dtype: object

In [119]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [120]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [122]:
obj = pd.Series(['a','a','b','c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object